"""Fit text to a measured style profile."""

from voicefit.distance import (
    AXES,
    DEFAULT_TOLERANCE,
    PUNCTUATION_AXIS,
    AxisDeviation,
    AxisSpec,
    ProfileDistance,
    compare_profiles,
    compare_text,
    compare_texts,
)
from voicefit.memory import (
    DEFAULT_CAPACITY,
    DEFAULT_ENDING_WORDS,
    DEFAULT_MAX_SHARE,
    DEFAULT_OPENING_WORDS,
    PATTERN_KINDS,
    OutputMemory,
    PatternUse,
    RepetitionReport,
    profile_key,
)
from voicefit.profile import (
    DEFAULT_HEDGES,
    SCHEMA_VERSION,
    StyleProfile,
    build_profile,
    split_paragraphs,
    split_sentences,
    tokenize_words,
)
from voicefit.rewrite import (
    Model,
    RewriteAttempt,
    RewriteConstraints,
    RewriteResult,
    build_instruction,
    rewrite,
)
from voicefit.spans import (
    PROTECTED_KINDS,
    ProtectedSpan,
    SpanCheck,
    SpanReport,
    extract_spans,
    verify_spans,
)

__all__ = [
    "AXES",
    "AxisDeviation",
    "AxisSpec",
    "DEFAULT_CAPACITY",
    "DEFAULT_ENDING_WORDS",
    "DEFAULT_HEDGES",
    "DEFAULT_MAX_SHARE",
    "DEFAULT_OPENING_WORDS",
    "DEFAULT_TOLERANCE",
    "Model",
    "OutputMemory",
    "PATTERN_KINDS",
    "PROTECTED_KINDS",
    "PUNCTUATION_AXIS",
    "PatternUse",
    "ProfileDistance",
    "ProtectedSpan",
    "RepetitionReport",
    "RewriteAttempt",
    "RewriteConstraints",
    "RewriteResult",
    "SCHEMA_VERSION",
    "SpanCheck",
    "SpanReport",
    "StyleProfile",
    "__version__",
    "build_instruction",
    "build_profile",
    "compare_profiles",
    "compare_text",
    "compare_texts",
    "extract_spans",
    "profile_key",
    "rewrite",
    "split_paragraphs",
    "split_sentences",
    "tokenize_words",
    "verify_spans",
]

__version__ = "0.1.0"
